### ISSUE TITLE
Update Version to Work with Activerecord 5?

### ISSUE THREAD

**Issue by jonmchan** [Trunkplatform/activerecord-db_exists#1]
Could you relax the version constraints on this gem to work with activerecord5? Pretty sure nothing changed to break functionality between 4 and 5. Just make the constraint:

```
spec.add_runtime_dependency "activerecord", "< 5.1", ">= 4.0"
```

**Comment by nagliyvred** [comment]
No problems @jonmchan . 
@simonhildebrandt would you able to change the ownership of this gem on rubygems.org so that I can publish a new version?

**Comment by simonhildebrandt** [comment]
@nagliyvred - I think I can do this... what email address should I add as another owner?

**Comment by nagliyvred** [comment]
Thanks Simon. bot-at-trunkplatform.com please!

**Comment by simonhildebrandt** [comment]
@nagliyvred - done. Feel free to yank me when you're sure it's working. :)

**Comment by jonmchan** [comment]
@nagliyvred bump? Could we get a new version released on rubygems?

**Comment by nagliyvred** [comment]
Sorry, I got lost in overseas travel. Done
